% load test file
tf = sltest.testmanager.load('TestDoorLockCntr.mldatx');

% run test
ro = tf.run();

% generate report
if(exist("TestResults", "dir") == 7)
    rmdir("TestResults");
end
mkdir("TestResults");

sltest.testmanager.report(ro, ...
    fullfile(pwd, "TestResults", 'testReport.pdf'),...
	'Author','MWtest',...
	'Title','Test',...
	'IncludeMLVersion',true,...
    'IncludeSimulationSignalPlots', true,...
    'IncludeComparisonSignalPlots', true,...
	'IncludeTestResults', 0,...
    'LaunchReport', false,...
    'IncludeCoverageResult', true);

% export results
sltest.testmanager.exportResults(ro, ...
    fullfile(pwd, "TestResults", 'testResults.mldatx'));