name: Model verification example for door lock control model

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PROJECTNAME: DemoBatchTokenGithub.prj
  ARTIFACTS_NAME: DLockCntr_ci_artifacts
  MLM_LICENSE_TOKEN: ${{ secrets.MyBatchToken }}

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

  verify:
    runs-on: self-hosted
    steps:
      - name: Run SLTest
        shell: cmd
        run: |
          matlab-batch "openProject('${{ env.PROJECTNAME }}');, runSLTest;
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sltest_artifact
          path: TestResults/**/*
