name: Model verification example for door lock control model

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PROJECTNAME: CruiseControlExample.prj
  ARTIFACTS_NAME: DLockCntr_ci_artifacts

jobs:
  verify:
    runs-on: self-hosted
    steps:
      - name: Run SLTest
        shell: cmdgit
        run: |
          matlab -batch "openProject('${{ env.PROJECTNAME }}');, runSLTest;